import Aeneas
import QrcertChecker.Types

/-!
Hand-written termination clauses for the Lean generated by the pinned Aeneas
bridge.  This file is copied to `QrcertChecker/Clauses/Clauses.lean` after
extraction.  It intentionally contains no behavioral model of the Rust code.
-/

open Aeneas Aeneas.Std Result ControlFlow Error

set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

namespace qrcert_checker

/- Every Rust error branch advances the index directly to the declared bound;
the success branch advances it by one checked addition. -/
@[simp]
def compute_checked_cost_loop_terminates
    (circuit : Circuit) (index : Std.U8) (_cost : Std.U32)
    (_error : Option CostError) : Nat :=
  circuit.num_ops.val - index.val

@[simp]
def decode_loop_terminates
    (_bytes : Slice Std.U8) (_n_qubits : Std.U8) (num_ops : Std.U8)
    (_ops : Array Op 256#usize) (_cursor : Std.Usize) (op_index : Std.U8)
    (_error : Option DecodeError) : Nat :=
  num_ops.val - op_index.val

end qrcert_checker

/- Tactic syntax must be registered at the module root so downstream generated
files receive it when importing this module. -/
macro "compute_checked_cost_loop_decreases" _circuit:ident index:ident
    _cost:ident _error:ident next_option:ident : tactic =>
  `(tactic| all_goals
    (have hindex := U8.checked_add_bv_spec $index 1#u8
     simp_wf <;> simp_all <;> simp_all [$next_option:ident] <;>
      scalar_decr_tac))

macro "decode_loop_decreases" _bytes:ident _n_qubits:ident
    _num_ops:ident _ops:ident _cursor:ident op_index:ident
    _error:ident next_option:ident : tactic =>
  `(tactic| all_goals
    (have hindex := U8.checked_add_bv_spec $op_index 1#u8
     simp_wf <;> simp_all <;> simp_all [$next_option:ident] <;>
      scalar_decr_tac))
